---
title: "Redgranite Group"
---

Redgranite Group creates data products, insights, and solutions for small-to-medium sized organizations.
 
Beyond our standard data science work, we also offer expert services related to music cognition, audio branding, and assessing and teaching adult learners on technical topics.

### Projects and Clients

- Dashboard for a client doing high six figure MRR
  + Developed bespoke expansion and churn metrics
  + Allowed client to identify at-risk customers
  + Created R package and Quarto reporting
- Report of revenue flow on sales team for rapidly growing tech company
  + Analyzed financial performance of team relative to spending
  + One time analysis to assist stakeholders

### Products

- [Bolero: Revenue/Ticket Dashboard for Arts Organizations](https://bolerodashboard.com)
- DB990: Searchable Database of 990 Tax Returns (Coming Soon...)

### Expert Services

Beyond my work in data science, I am an expert in music perception and cognition ([former life as academic](https://scholar.google.com/citations?user=tigU2AkAAAAJ&hl=en)).
I have also worked extensively both delivering technical training and assessing adult learners in data science.
Below are a few clients and projects that I've worked on because of this expertise.

#### Audio Branding

- Designed scientific studies with [MassiveMusic](https://massivemusic.com/) for [GSK](https://www.gsk.com/en-gb/)
- Expert for internal [Panasonic](https://www.panasonic.eu/rituals/) project
- Scientist on [Music for Brainwaves](https://www.erasedtapes.com/release/eratp120-various-artists-music-for-brainwaves) project
- Assisted with development of [Soundout’s](https://www.soundout.com/) original Brand Match tool

#### Assessing Adult Learners on Technical Topics

- I've assessed over 80 Master's level machine learning capstone projects for [DSW](https://www.dswlearning.co.uk/end-point-assessment/)
- Developed internal marking criteria in accordance with [UK Government Standard](http://findapprenticeshiptraining.apprenticeships.education.gov.uk/courses/457)

