---
title: "Hello!"
---

I am a data scientist, small business owner, and lifelong learner. 
My consultancy, [Redgranite Group](about.qmd), develops data products and insights for small-to-medium sized businesses.
I work well in interdisciplinary teams, previous colleagues include: psychologists, computer scientists, music theorists, genomicists, software engineers, and educators. 
I have strong opinions about R, Bayesian statistics, jazz, and GTD.

::: {.callout-note collapse="true"}
## Actively Looking for Longer-Term Work
I spent the last year working on freelance/consultancy projects (during move from Europe to USA) and I’m now looking for more stable, longer-term work (e.g. full-time, long-contract). 

If you're looking to hire someone with a strong foundation in the bread-and-butter data workflow (wrangling, visualising, modelling, communicating), [get in touch](mailto:director@redgranite.group)!
:::

Links

- [Redgranite Group](about.qmd)
- [Bolero](https://www.bolerodashboard.com) 
- [LinkedIn](https://www.linkedin.com/in/david-john-baker-phd/)
- [Github](https://github.com/davidjohnbaker1)
- [Scholar](https://scholar.google.com/citations?user=tigU2AkAAAAJ&hl=en)
- [Personal Blog](https://davidjohnbaker.rbind.io/)
- [Bluesky](https://bsky.app/profile/davidjohnbaker.bsky.social) 

Background

- 2024-Now : Data Scientist, Director of [Redgranite Group](www.redgranite.group)
- 2022-2024: Postdoc at the [Music Cognition Group](https://www.mcg.uva.nl/) at the [University of Amsterdam](https://www.uva.nl/)
- 2021-2022: Postdoc in the [Department of Psychology](https://www.gold.ac.uk/psychology/) at [Goldsmiths](https://www.gold.ac.uk/)
- 2020-2021: Senior Research Associate in the [Computing Department](https://www.gold.ac.uk/computing/) at [Goldsmiths](https://www.gold.ac.uk/)
- 2019-2020: Lead Instructor of Data Science at [Flatiron School](https://flatironschool.com/) in London, England
- 2015-2019: PhD student at [Louisiana State University](https://lsu.edu/); [Thesis](https://repository.lsu.edu/gradschool_dissertations/4960/)
- 2014-2015: Research Assistant on an [AHRC funded project](https://tm.web.ox.ac.uk/). 
- 2013-2014: MSc student in the [Music, Mind and Brain](https://www.gold.ac.uk/pg/msc-music-mind-brain/) programme at [Goldsmiths](https://www.gold.ac.uk/)
- 2012-2013: Musician and bartender for weddings at a WWII themed restaurant
- 2008-2012: Music student at [Baldwin Wallace Conservatory of Music](https://www.bw.edu/schools/conservatory/)
- I grew up in Wisconsin. 

Recent Talks 

- [How Building a MicroSaas in R might make you a better data scientist](https://github.com/davidjohnbaker1/tug_talk_2025) @ [Northeast Tableau User Group](https://usergroups.tableau.com/events/details/tableau-northern-new-england-tableau-user-group-presents-northern-new-england-tug-march-2025-edition/)
- [Characterizing musicality and individual differences within and across societies using engaging games: A Case Study Using the Matching Pairs Paradigm](https://github.com/Amsterdam-Music-Lab/nwo-oc-matching-pairs-talk) @ Goldsmiths University of London
- [Musical Memory Experiments for Everyone (including Experts!)](https://davidjohnbaker.rbind.io/posts/2023-10-18-musical-memory-experiments-for-everyone-including-experts/) @ University of Cambridge
